### ISSUE TITLE
Undetected keypoint confused with the point of (0, 0)

### ISSUE THREAD

**Issue by yw155** [matteorr/coco-analyze#14]
Hi @matteorr, thanks for your great work. I would like to ask a question that is there a way to handle the case that undetected keypoint assigned to (0, 0) is considered as the prediction.
I obtained some analyzed results as follows. We can see each type of error has such a case. I think it may generate incorrect analysis. Thank you.
Inversion
![screenshot from 2018-07-24 17-47-07](https://user-images.githubusercontent.com/20606278/43153618-a906ac02-8f69-11e8-937a-361adde4fb1d.png)
Jitter
![screenshot from 2018-07-24 17-49-17](https://user-images.githubusercontent.com/20606278/43153767-1a12552c-8f6a-11e8-9451-891875c260e5.png)
Miss
![screenshot from 2018-07-24 17-49-49](https://user-images.githubusercontent.com/20606278/43153775-230f536e-8f6a-11e8-9921-ecc1edd798b8.png)
Swap
![screenshot from 2018-07-24 17-50-12](https://user-images.githubusercontent.com/20606278/43153794-2b2d902e-8f6a-11e8-89e3-c31cf5882f14.png)

**Comment by matteorr** [comment]
@yw155 - Thanks for pointing this out. Could you please share a bit more details on how to reproduce this bug? Is this happening in the [localization errors function](https://github.com/matteorr/coco-analyze/blob/release/analysisAPI/localizationErrors.py)? And what version of the COCO dataset are you using (i.e. 2014 or 2017)? I'll look into it right now, but the more info you give me the easier it'll be to spot it.

**Comment by yw155** [comment]
Hi @matteorr, thanks for your reply. I just found the above outputs from the folder of 'localization_errors/keypoints_breakdown'. And I use COCO 2017. Is it possible that the bug exists after the OKS matching and evaluation considers the point of (0, 0)? Thanks.

**Comment by matteorr** [comment]
I'll look into it.Could you post or send me a link to where I can download your json detections?

**Comment by yw155** [comment]
Hi @matteorr, the file is here:
[coco_val2017-1_4.zip](https://github.com/matteorr/coco-analyze/files/2263449/coco_val2017-1_4.zip)

**Comment by matteorr** [comment]
Hey @yw155, this [commit](https://github.com/matteorr/coco-analyze/commit/c5c6009fe11823a59c7f04704cc6adf0e572edfc) fixes the problem.

The reason the visualizations contained keypoints in (0,0) is that your algorithm predicts keypoints that are not visible (i.e. visibility flag is 0) in location (0,0), while all of the algorithms I previously analyzed always make a prediction for all the keypoints in the skeleton, regardless of the value of the visibility flags.

You now have the option in the [localizationErrors file](https://github.com/matteorr/coco-analyze/blob/release/analysisAPI/localizationErrors.py#L157) to set a variable `USE_VISIBILITY_FOR_PLOTS` such that when plotting the detections the value of the visibility flag will be taken in consideration and only keypoints whos visibility is 1 (visible but occluded), or 2 (visible) will be plotted.

**NOTE:** This _bug_ isn't really a _bug_, but more of a difference in the outputs of the algorithms, and only affects the plotting but not the evaluation and analysis itself since that already takes into account the visibility. Nonetheless thanks for pointing it out!

**Comment by yw155** [comment]
Hi @matteorr, I got that. Thanks for your detailed analysis. The commit is great.

**Comment by WillBrennan** [comment]
Just hit this, it might be good to put a comment about this on the readme?

**Comment by matteorr** [comment]
@WillBrennan  - Great suggestion! Thanks for your contributions to the repo, small details can make a big difference.
