### ISSUE TITLE
Swapped keypoints

### ISSUE THREAD

**Issue by yw155** [matteorr/coco-analyze#2]
Hi @matteorr , could you illustrate how to compute the swapped keypoints in your code? I notice that in line 326 of cocoanalyze.py, the swapped keypoints are computed as:
`# swapped keypoints are those that have oks => 0.5 but on keypoint of other person
swap_kpts  = np.logical_and.reduce((oks_max >= self.params.jitterKsThrs[0], oks_argmax != 0, oks_argmax != num_anns))
swap_kpts  = np.logical_and(swap_kpts, gt_kpt_v != 0)*1`
but I am not understand the meaning of 'oks_argmax != 0 & oks_argmax !=num_anns' at here.
Thank you.

**Comment by matteorr** [comment]
The code you are asking about is in the function `_find_kpt_errors()`. This function loops ([line 215](https://github.com/matteorr/coco-analyze/blob/release/pycocotools/cocoanalyze.py#L215)) over all the detections that have been matched with a ground truth annotations and computes for that detection all the types of keypoint errors that occurred.

#### 1) Build a matrix containing all the ground truth keypoints

The matrix `gts_kpt_mat` has [dimensions 2*num_anns x 2*k](https://github.com/matteorr/coco-analyze/blob/release/pycocotools/cocoanalyze.py#L254) and is constructed in such a way that:

- Row 0 [contains the keypoints of the ground truth](https://github.com/matteorr/coco-analyze/blob/release/pycocotools/cocoanalyze.py#L272-L279) that was matched with the specific detection that is being analysed at a certain iteration of the loop.

- Row `i + num_anns` contains the keypoints of the ground truth in Row i inverted according to the inverted keypoint list provided [here](https://github.com/matteorr/coco-analyze/blob/release/pycocotools/cocoanalyze.py#L914-L922). For instance, the  keypoint `left_ear` has x and y coordinates in position 6,7 for the original keypoints but in position 8,9 for the inverted keypoints.

#### 2) Compute the OKS between the detection keypoints and all rows of the ground truth keypoints

The matrix `kpt_oks_mat` has [dimensions 2n x k](https://github.com/matteorr/coco-analyze/blob/release/pycocotools/cocoanalyze.py#L296-L298) and contains for every keypoint in the [`dt_kpt_arr`](https://github.com/matteorr/coco-analyze/blob/release/pycocotools/cocoanalyze.py#L225) its OKS with the corresponding keypoint in all the ground truth annotations and their inverted versions. 

For instance column 3 contains the OKS of the `left_ear` of the detection with the `left_ear` of all the ground truth annotations (in rows 0 to `num_anns`) and the `right_ear` of all the ground_truth annotations (in rows `num_anns` to `2*num_anns`).

#### 3) Compute the type of error based on the max and argmax of the keypoints OKS matrix

Because of the properties of `gts_kpt_mat` it is now very easy to determine the type of error (if present) by simply looking at the [max and argmax](https://github.com/matteorr/coco-analyze/blob/release/pycocotools/cocoanalyze.py#L307-L310) value of `kpt_oks_mat` along dimension 0:

- [Good Keypoints](https://github.com/matteorr/coco-analyze/blob/release/pycocotools/cocoanalyze.py#L312-L314):  Are those for which the highest OKS is in row 0 (which corresponds to the ground truth matched with this detection) and the OKS value is greater than the [jitter threshold interval](https://github.com/matteorr/coco-analyze/blob/release/pycocotools/cocoanalyze.py#L931).
```
oks_max > self.params.jitterKsThrs[1],
oks_argmax == 0
```

- [Jitter Error](https://github.com/matteorr/coco-analyze/blob/release/pycocotools/cocoanalyze.py#L316-L319): Are those for which the highest OKS is in row 0 (which corresponds to the ground truth matched with this detection) and the OKS value is inside the [jitter threshold interval](https://github.com/matteorr/coco-analyze/blob/release/pycocotools/cocoanalyze.py#L931).
```
oks_max >= self.params.jitterKsThrs[0],
oks_max < self.params.jitterKsThrs[1],
oks_argmax == 0
```

- [Inversion Error](https://github.com/matteorr/coco-analyze/blob/release/pycocotools/cocoanalyze.py#L321-L323): Are those for which the highest OKS is in row num_anns (which corresponds to the inverted keypoint of the ground truth matched with this detection) and the OKS value is inside the [jitter threshold interval](https://github.com/matteorr/coco-analyze/blob/release/pycocotools/cocoanalyze.py#L931).
```
oks_max >= self.params.jitterKsThrs[0],
oks_argmax == num_anns
```

- [Swap Error](https://github.com/matteorr/coco-analyze/blob/release/pycocotools/cocoanalyze.py#L325-L328): Are those for which the highest OKS has value inside the [jitter threshold interval](https://github.com/matteorr/coco-analyze/blob/release/pycocotools/cocoanalyze.py#L931), however it is not in row 0 (matched ground truth) or in row `num_anns` (inverted matched ground truth), which means that it is on another person (regardless of which person).
```
oks_max >= self.params.jitterKsThrs[0],
oks_argmax != 0, 
oks_argmax != num_anns
```

- [Miss Error](https://github.com/matteorr/coco-analyze/blob/release/pycocotools/cocoanalyze.py#L330-L332): Are those for which the OKS value is smaller than the [jitter threshold interval](https://github.com/matteorr/coco-analyze/blob/release/pycocotools/cocoanalyze.py#L931), regardless of the row in which they occurred.
```
oks_max < self.params.jitterKsThrs[0]
```

Hope this helps.

**Comment by yw155** [comment]
Thanks for your detailed explanations.
