### ISSUE TITLE
Using Train Data For Benchmarks Confusion

### ISSUE THREAD

**Issue by H19012** [matteorr/coco-analyze#21]
Why was coco train 2014 used for the benchmark jsons instead of validation data? Doesn't this result in inference using train data? I don't quite understand it.

**Comment by matteorr** [comment]
Obviously, the analysis is run on the coco test set. 

However, since it is kept private, I did not release any information about those annotations, but only the overall performance results of my analysis on it.

On the contrary, I could release the ground-truth information (such as the number of annotation instances in each benchmark and their corresponding ids) from the data in coco train 2014, which is what is publicly available on my website.

Please let me know if you need further clarifications.
