### ISSUE TITLE
About Histogram Plot of False Positive Scores

### ISSUE THREAD

**Issue by H19012** [matteorr/coco-analyze#22]
In histogram plot of false positive scores along with different percentile, we can see that for lower percentile false positives scores are high. In the generated text file for each percentile there are a score and number of detection. i.e. Percentiles of the scores of all Detections:
 - 20th perc. score:[0.004]; num. dts:[1802]
 - 40th perc. score:[0.154]; num. dts:[3603]
 - 60th perc. score:[0.378]; num. dts:[5404]
 - 80th perc. score:[0.554]; num. dts:[7205]

	
Here in X-axis mean percentile, so why in X-axis values are not evenly distributed?
	What does the Y-axis value mean? And how do you get the value?

**Comment by matteorr** [comment]
Would you mind providing a few more details? What code did you run, what file did you get the percentiles form? Please be more specific so I can help you better, and so whoever reads this issue can understand better what you are referring to. Thanks!

**Comment by H19012** [comment]
> Would you mind providing a few more details? What code did you run, what file did you get the percentiles form? Please be more specific so I can help you better, and so whoever reads this issue can understand better what you are referring to. Thanks!

After looking at your supplementary PDF(http://www.vision.caltech.edu/~mronchi/papers/ICCV17_PoseErrorDiagnosis_SUPP.pdf page 7), specifically the "Background False Negatives Analysis" figures, my confusion went away. Thank you for your reply.

**Comment by H19012** [comment]
Sorry to bother again, but just to make sure here is my question:-
![Annotation 2020-04-24 112543](https://user-images.githubusercontent.com/60960749/80168751-a1ce1580-861e-11ea-91b6-5c77d913b90d.jpg)
![Annotation 2020-04-24 112616](https://user-images.githubusercontent.com/60960749/80168758-a5fa3300-861e-11ea-989a-08ce808897d5.jpg)

What does the height of these bins signify? And also for the blue graph, is the right most bin same as summation of Background FP or not( if the threshold is set so that only FPs in the 80th percentile are considered FP)?

**Comment by matteorr** [comment]
The first plot is the histogram of the confidence scores for false positive detections. The analysis code looks at all the scores of the provided detections and then plots the histogram of scores only for the false positives. 

A high score false positive is problematic, as it means that your algorithm is making a bad prediction with high confidence. In that histogram you can see how many false positives you have for the 20th, 40th, 60th and 80th percentile of all detection scores.  Note that you could change the percentiles to be whichever ones you prefer in [backgroundFalsePosErrors.py](https://github.com/matteorr/coco-analyze/blob/506563803d5e86bd5abc0100daf24fbae210790d/analysisAPI/backgroundFalsePosErrors.py#L53-L54).

The second plot is a histogram of area sizes for false positive or false negative detections (can't tell which from the snapshot since the analysis code creates an histogram for both). This is meant to show you what area sizes do you typically have for false positive or false negatives. For instance, if you have many small false positives it could suggest that your algorithm is detecting a lot of small people that are not truly people.

Hopefully this cleared your doubts, feel free to re-open if you still have questions.
